### ISSUE TITLE
InternalOAuthError: Failed to fetch user profile crashes server

### ISSUE THREAD

**Issue by lucahammer** [lucahammer/fedifinder#104]
```
Error: Cannot find module '/app/warnings'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by lucahammer** [comment]
Related?

`node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:57

        return new types_1.ApiRequestError('Request failed.', {

               ^

ApiRequestError: Request failed.

    at RequestHandlerHelper.createRequestError (/rbd/pnpm-volume/463b6737-3f01-4ee0-b330-e2d2c368212e/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:57:16)

    at RequestHandlerHelper.requestErrorHandler (/rbd/pnpm-volume/463b6737-3f01-4ee0-b330-e2d2c368212e/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:216:21)

    at ClientRequest.emit (node:events:526:28)

    at TLSSocket.socketErrorListener (node:_http_client:442:9)

    at TLSSocket.emit (node:events:526:28)

    at emitErrorNT (node:internal/streams/destroy:157:8)

    at emitErrorCloseNT (node:internal/streams/destroy:122:3)

    at processTicksAndRejections (node:internal/process/task_queues:83:21) {

  error: true,

  type: 'request'

}`
