### ISSUE TITLE
Cannot read properties of undefined (reading 'length') in sorted_domains

### ISSUE THREAD

**Issue by nepeat** [lucahammer/fedifinder#175]
Hi! Cutting a ticket since something happened when I tried to scan my followers (@eggrins)

```
Proxy {error: 'not a handle or not a domain'} client.js:245

5vue.prod.js:1 TypeError: Cannot read properties of undefined (reading 'length')
    at Proxy.sorted_domains (client.js:141:36)
    at Ve.run (vue.prod.js:1:5614)
    at get value [as value] (vue.prod.js:1:13708)
    at Object.get [as sorted_domains] (vue.prod.js:1:31511)
    at Object.get (vue.prod.js:1:29556)
    at Object.get (vue.prod.js:1:30460)
    at Proxy.render (eval at ba (vue.prod.js:1:1), <anonymous>:401:172)
    at kn (vue.prod.js:1:15996)
    at Ve.fn (vue.prod.js:1:46164)
    at Ve.run (vue.prod.js:1:5614)
```

Buggy portion of code clipped below for reference.
```
    sorted_domains() {
      let sorted = [];
      for (const [domain, data] of Object.entries(this.domains)) {
        sorted.push([
          {
            domain: domain,
            local_domain: data.local_domain ? data.local_domain : domain,
            software_name: data.software_name,
            software_version: data.software_version,
            users_total: data.users_total,
            contacts: data.handles.length, // issue is here
            openRegistrations: data.openRegistrations,
            part_of_fediverse: data.part_of_fediverse,
          },
          data.handles.length,
        ]);
      }
      sorted.sort(function (a, b) {
        return b[1] - a[1];
      });
      return sorted;
    },
```

**Comment by nepeat** [comment]
I was poking at it and saw `undefined: {error: 'not a handle or not a domain'}` got pushed to `this.domains`. Maybe expect a PR from me shortly!
