### ISSUE TITLE
Fatal error on OAuth return page

### ISSUE THREAD

**Issue by ivovegter** [lucahammer/fedifinder#89]
After authorising Twitter access, the return page says:

ReferenceError: data is not defined
    at Strategy._verify (/app/server.js:58:36)
    at /rbd/pnpm-volume/463b6737-3f01-4ee0-b330-e2d2c368212e/node_modules/passport-oauth1/lib/strategy.js:192:24
    at /rbd/pnpm-volume/463b6737-3f01-4ee0-b330-e2d2c368212e/node_modules/passport-twitter/lib/strategy.js:158:7
    at passBackControl (/rbd/pnpm-volume/463b6737-3f01-4ee0-b330-e2d2c368212e/node_modules/oauth/lib/oauth.js:390:11)
    at IncomingMessage.<anonymous> (/rbd/pnpm-volume/463b6737-3f01-4ee0-b330-e2d2c368212e/node_modules/oauth/lib/oauth.js:409:9)
    at IncomingMessage.emit (node:events:538:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

No idea what this means, but it does break the service.

**Comment by lucahammer** [comment]
I introduced a bug with a hot fix to reduce the data that's stored in the sessions store. It's fixed now.
